name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: "just-a-placeholder"

      - name: Add remote host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            # --- Step 1: Navigate to project directory ---
            echo "--> Navigating to project directory..."
            cd /var/www/beatcaster || exit 1
            pwd
            
            # --- Step 2: Pull latest code from Git ---
            echo "--> Pulling latest code..."
            git pull
            
            # --- Step 3: Install dependencies ---
            echo "--> Installing NPM dependencies..."
            npm install
            
            # --- Step 4: Deleting old build cache ---
            echo "--> Deleting old .next folder..."
            rm -rf .next
            ls -l | grep .next || echo ".next directory not found, which is good."
            
            # --- Step 5: Building the application ---
            echo "--> Building Next.js application..."
            npm run build
            
            # --- Step 6: Checking new build output ---
            echo "--> Listing contents of new .next folder..."
            ls -lh .next/
            
            # --- Step 7: Restarting the application service ---
            echo "--> Restarting beatcaster.service..."
            sudo systemctl restart beatcaster.service
            sleep 5 # Wait 5 seconds for the service to stabilize
            sudo systemctl status beatcaster.service
            
            echo "--> DEPLOYMENT SCRIPT FINISHED <--"
          EOF
